name: focus_life
description: A focus app with life progression
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.1





  # App monitoring
  app_usage: ^4.0.1

  # Background service
  flutter_background_service: ^5.1.0
  workmanager: ^0.7.0

  # Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State management
  provider: ^6.1.5

  app_settings: ^5.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/animations/flame.riv
    - assets/animations/bob_idle.riv
    - assets/images/cave_background.png
    - assets/images/house.png
    - assets/images/shack.png
    - assets/images/cave.png
    - assets/images/cave_background.png
    - assets/images/shack_background.png
    - assets/images/house_background.png
    - assets/images/door1.png
    - assets/images/door2.png
    - assets/images/house_bedroom_background.png
    - assets/images/stone_fire.png
    - assets/images/stone_bed.png
    - assets/images/stone_rug.png
    - assets/images/stone_table.png
    - assets/images/stone_chair.png
    - assets/images/shack_bed.png
    - assets/images/shack_stove.png
    - assets/images/shack_table.png
    - assets/images/shack_picture.png
    - assets/images/house_table.png
    - assets/images/house_stove.png
    - assets/images/house_cabinet.png
    - assets/images/house_light.png
    - assets/images/house_fridge.png
    - assets/images/house_bunkbed.png
    - assets/images/house_bed.png
    - assets/images/house_desk.png
    - assets/images/house_clock.png
    - assets/images/house_picture.png


