name: focus_life
description: A focus app with life progression
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.1

  # App monitoring
  app_usage: ^4.0.1

  # Storage
  shared_preferences: ^2.5.3

  app_settings: ^5.1.1

  cupertino_icons: ^1.0.2

  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

  audioplayers: ^6.0.0

  share_plus: ^10.0.0
  path_provider: ^2.1.5
  flutter_foreground_task: ^8.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/animations/bob_idle.riv
    - assets/images/cave_background.png
    - assets/images/house.png
    - assets/images/shack.png
    - assets/images/cave.png
    - assets/images/shack_background.png
    - assets/images/house_background.png
    - assets/images/house_bedroom_background.png
    - assets/images/stone_fire.png
    - assets/images/stone_bed.png
    - assets/images/stone_rug.png
    - assets/images/stone_table.png
    - assets/images/stone_chair.png
    - assets/images/shack_bed.png
    - assets/images/shack_stove.png
    - assets/images/shack_table.png
    - assets/images/shack_picture.png
    - assets/images/house_table.png
    - assets/images/house_stove.png
    - assets/images/house_cabinet.png
    - assets/images/house_light.png
    - assets/images/house_fridge.png
    - assets/images/house_bunkbed.png
    - assets/images/house_bed.png
    - assets/images/house_desk.png
    - assets/images/house_clock.png
    - assets/images/house_picture.png
    - assets/sounds/achievement.wav
    - assets/sounds/background_music.mp3
    - assets/sounds/coin_convert.wav
    - assets/sounds/daily_reward.wav
    - assets/sounds/focus_music.mp3
    - assets/sounds/purchase.wav
    - assets/sounds/session_complete.wav
    - assets/images/icon.png