import 'dart:math';

class FactsService {
  static final FactsService _instance = FactsService._internal();
  factory FactsService() => _instance;
  FactsService._internal();

  final Random _random = Random();
  int? _lastFactIndex;

  // 400+ Cool Facts Database
  final List<String> _facts = [
    // Science Facts (100)
    "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that's still edible!",
    "A day on Venus is longer than a year on Venus. It takes 243 Earth days to rotate once, but only 225 days to orbit the Sun.",
    "Bananas are berries, but strawberries aren't. Botanically, berries come from one flower with one ovary.",
    "Your brain uses 20% of your body's energy while being only 2% of your body weight.",
    "Octopuses have three hearts and blue blood. Two hearts pump blood to the gills, one pumps to the body.",
    "Water can boil and freeze at the same time - it's called the triple point!",
    "Glass is actually a liquid, not a solid - it just flows VERY slowly over centuries.",
    "A single lightning bolt contains enough energy to power a house for a month.",
    "Helium makes your voice higher because sound travels faster through it than air.",
    "Diamonds rain on Jupiter and Saturn - pressure turns methane into carbon crystals!",
    "Hot water freezes faster than cold water - it's called the Mpemba effect.",
    "Your body contains enough iron to make a 3-inch nail.",
    "Sound travels 4 times faster in water than in air.",
    "A teaspoon of honey is the life work of 12 bees.",
    "Graphite and diamonds are made of the same atoms, just arranged differently.",
    "Stomach acid is strong enough to dissolve metal, but mucus protects your stomach lining.",
    "A single bolt of lightning is 5 times hotter than the surface of the sun.",
    "Sharks existed before trees - they're over 400 million years old!",
    "Your DNA stretched out would reach from Earth to the Sun 600 times.",
    "Butterflies can taste with their feet to find good plants for laying eggs.",
    "Polar bears are nearly invisible to infrared cameras - their fur is that good at insulation!",
    "A single sneeze travels at 100 mph and can spray droplets 30 feet.",
    "Your fingernails grow 4 times faster than your toenails.",
    "The average person walks the equivalent of 5 times around the world in their lifetime.",
    "Your stomach gets a new lining every 3-4 days to prevent self-digestion.",
    "A cockroach can live for weeks without its head before dying of starvation.",
    "Your eyes can distinguish between 10 million different colors.",
    "The human body glows - you emit light 1,000 times weaker than your eyes can see.",
    "Your heart beats 100,000 times per day, pumping 2,000 gallons of blood.",
    "Humans shed about 40 pounds of skin in their lifetime.",
    "Your brain generates 25 watts of power while awake - enough to power a light bulb!",
    "Blood makes up 8% of your body weight.",
    "You produce enough saliva in your lifetime to fill two swimming pools.",
    "Your bones are 5 times stronger than steel of the same density.",
    "The human eye blinks an average of 4,200,000 times per year.",
    "Your body has enough carbon to make 900 pencils.",
    "Stomach acid (pH 1-2) can dissolve razor blades.",
    "You lose about 100 hairs per day naturally.",
    "Your tongue print is unique, just like fingerprints.",
    "The strongest muscle in the human body is the masseter (jaw muscle).",
    "Babies are born with 300 bones, but adults only have 206 (some fuse together).",
    "Your nose can remember 50,000 different scents.",
    "The average person spends 6 months of their life waiting for red lights to turn green.",
    "You can't breathe and swallow at the same time (try it!).",
    "Your brain uses 20 watts of power - less than a refrigerator light bulb.",
    "The human brain is 73% water - even 2% dehydration affects performance.",
    "Your heart will beat about 3 billion times in your lifetime.",
    "Humans are the only animals that blush.",
    "Your lungs have a surface area equal to a tennis court when flattened.",
    "You have more bacteria cells than human cells in your body (by count, not mass).",

    // Space Facts (50)
    "One million Earths could fit inside the Sun. The Sun contains 99.86% of the mass in our solar system.",
    "There are more stars in the universe than grains of sand on all Earth's beaches - about 10^24 stars!",
    "A teaspoon of neutron star material would weigh 6 billion tons on Earth.",
    "Saturn's rings are only about 30 feet thick despite being 175,000 miles wide.",
    "The footprints on the Moon will stay there for millions of years - there's no wind to blow them away!",
    "Space is completely silent - there's no atmosphere to carry sound.",
    "Venus spins backwards compared to most planets.",
    "Olympus Mons on Mars is 3 times taller than Mount Everest.",
    "The International Space Station travels at 17,500 mph - circling Earth every 90 minutes.",
    "A day on Mercury (59 Earth days) is longer than its year (88 Earth days).",
    "The Milky Way galaxy smells like rum and tastes like raspberries (based on chemical analysis).",
    "Neutron stars can spin 600 times per second.",
    "There's a planet made entirely of diamond (55 Cancri e) - it's twice the size of Earth!",
    "The Great Red Spot on Jupiter is a storm that's been raging for at least 400 years.",
    "Mars sunsets are blue, not orange.",
    "A year on Pluto is 248 Earth years long.",
    "The coldest place in the universe is on Earth - in a lab where scientists achieved 0.0000000001 degrees above absolute zero.",
    "Black holes aren't actually black - they glow due to radiation.",
    "The Sun loses a billion kilograms of mass per second.",
    "Saturn would float in water - its density is less than water's.",
    "The universe is expanding faster than the speed of light.",
    "There are rogue planets that drift through space without orbiting a star.",
    "Jupiter has 79 known moons (and counting).",
    "A sunset on Mars lasts about 2 hours.",
    "The hottest planet is Venus, not Mercury (despite being farther from the Sun).",
    "Earth isn't perfectly round - it's slightly flattened at the poles.",
    "The Hubble Space Telescope travels at 5 miles per second.",
    "Uranus rotates on its side - its axis is tilted 98 degrees.",
    "The Moon is moving away from Earth at 1.5 inches per year.",
    "Neptune takes 165 Earth years to orbit the Sun once.",
    "The Andromeda galaxy is approaching us at 250,000 mph.",
    "There's a water vapor cloud in space that contains 140 trillion times all the water on Earth.",
    "The temperature on the Moon ranges from -173°C at night to 127°C in the day.",
    "Mercury has ice in its polar craters despite being close to the Sun.",
    "Jupiter's moon Europa has a liquid ocean beneath its icy surface.",
    "The asteroid belt contains only 4% of the Moon's mass despite millions of asteroids.",
    "Light from some stars takes billions of years to reach us - we see the past when looking at space.",
    "Pluto hasn't completed one orbit around the Sun since its discovery in 1930.",
    "The Voyager 1 spacecraft is 14 billion miles from Earth and still sending data.",
    "Astronauts can't cry in space - tears just pool up in balls due to lack of gravity.",
    "Saturn's rings are made of ice and rock chunks, some as small as grains of sand.",
    "The Sun is so large that its gravity keeps planets in orbit from 3 billion miles away.",
    "Mars has the largest dust storms in the solar system - they can engulf the entire planet.",
    "The temperature at the core of the Sun is 15 million degrees Celsius.",
    "There are more possible chess games than atoms in the observable universe.",
    "The cosmic microwave background radiation is the oldest light in the universe (13.8 billion years old).",
    "Jupiter's magnetic field is 20,000 times stronger than Earth's.",
    "A supernova can outshine an entire galaxy for weeks.",
    "Time moves slower near massive objects due to gravity (proven by GPS satellites!).",
    "The nearest star system (Alpha Centauri) is 4.37 light years away - that's 25 trillion miles!",

    // Animal Facts (100)
    "Octopuses can taste with their arms. Each sucker has chemoreceptors to identify food.",
    "Cows have best friends and get stressed when separated from them.",
    "A group of flamingos is called a 'flamboyance' - perfectly named!",
    "Dolphins have names for each other and call out to specific individuals.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "A shrimp's heart is in its head.",
    "Elephants are the only animals that can't jump.",
    "A group of owls is called a 'parliament'.",
    "Penguins propose to their mates with a pebble - if accepted, they mate for life.",
    "Wombat poop is cube-shaped to prevent it from rolling away (they use it to mark territory).",
    "Sloths can hold their breath longer than dolphins - up to 40 minutes!",
    "A group of pugs is called a 'grumble'. Perfect!",
    "Horses can't breathe through their mouths - only through their noses.",
    "A snail can sleep for 3 years straight.",
    "Hummingbirds are the only birds that can fly backwards.",
    "Koalas sleep 22 hours a day.",
    "Giraffes have the same number of neck bones as humans (7).",
    "A cat has 32 muscles in each ear.",
    "Bees can recognize human faces.",
    "Crows can hold grudges against people for years.",
    "Male seahorses get pregnant, not females.",
    "A group of crows is called a 'murder'.",
    "Squirrels plant thousands of trees by forgetting where they buried their acorns.",
    "A pig's orgasm lasts 30 minutes.",
    "Otters have a pocket in their skin to store their favorite rock.",
    "Elephants can recognize themselves in mirrors.",
    "Dogs can smell your feelings - they detect hormonal changes.",
    "A blue whale's heart weighs 400 pounds.",
    "Mantis shrimp can punch so fast they boil the water around their fist.",
    "Cheetahs can't roar - they meow like house cats.",
    "A group of jellyfish is called a 'smack'.",
    "Butterflies taste with their feet.",
    "Turtles can breathe through their butts.",
    "A group of pandas is called an 'embarrassment'.",
    "Honeybees can fly up to 15 mph.",
    "A blue whale's tongue weighs as much as an elephant.",
    "Pigeons can do math - they can learn to count up to 9.",
    "Frogs drink water through their skin, not their mouths.",
    "A group of ravens is called an 'unkindness'.",
    "Parrots can live up to 80 years.",
    "Bats always turn left when exiting a cave.",
    "A group of ferrets is called a 'business'.",
    "Chameleons change color based on mood, not surroundings.",
    "A group of hedgehogs is called a 'prickle'.",
    "Wolves howl in different pitches so they sound like more wolves than they are.",
    "A polar bear's skin is black under its white fur.",
    "Kangaroos can't walk backwards.",
    "A group of rhinoceroses is called a 'crash'.",
    "Alligators can live up to 100 years.",
    "A group of zebras is called a 'dazzle'.",
    "Camels have three eyelids to protect against sand.",
    "A group of hippos is called a 'bloat'.",
    "Hummingbirds' hearts beat 1,200 times per minute.",
    "A group of porcupines is called a 'prickle'.",
    "Ostriches can run faster than horses and male ostriches can roar like lions.",
    "A group of alligators is called a 'congregation'.",
    "Reindeer eyes turn blue in winter to see better in the dark.",
    "A group of toads is called a 'knot'.",
    "Narwhals are real! Their tusk is actually a tooth with 10 million nerve endings.",
    "A group of sharks is called a 'shiver'.",
    "Goats have rectangular pupils.",
    "A group of fish is called a 'school' but also a 'shoal'.",
    "Rats laugh when tickled.",
    "A group of geese on the ground is a 'gaggle', but in the air it's a 'skein'.",
    "A woodpecker's tongue wraps around its brain to protect it from impact.",
    "A group of butterflies is called a 'kaleidoscope'.",
    "Axolotls can regenerate entire limbs.",
    "A group of bats is called a 'colony' or 'cloud'.",
    "Naked mole rats don't age - they look the same their entire life.",
    "A group of cats is called a 'clowder' or 'glaring'.",
    "Platypuses don't have stomachs.",
    "A group of larks is called an 'exaltation'.",
    "Lobsters pee out of their faces.",
    "A group of peacocks is called an 'ostentation'.",
    "Komodo dragons can reproduce asexually through parthenogenesis.",
    "A group of turkeys is called a 'rafter'.",
    "Vampire bats will adopt orphaned baby bats.",
    "A group of vultures is called a 'committee' when resting and a 'kettle' when flying.",
    "Octopuses have 9 brains - one main brain and one in each arm.",
    "A group of eagles is called a 'convocation'.",
    "Hummingbirds are the only birds that can hover in place.",
    "A group of magpies is called a 'mischief' or 'charm'.",
    "Flying squirrels don't actually fly - they glide up to 300 feet.",
    "A group of sparrows is called a 'host'.",
    "Sea horses mate for life and travel holding each other's tails.",
    "A group of swallows is called a 'gulp'.",
    "Honey badgers are immune to snake venom.",
    "A group of parrots is called a 'pandemonium'.",
    "Ants don't sleep.",
    "A group of ravens eating together is called an 'unkindness'.",
    "Electric eels can generate 600 volts of electricity.",
    "A group of starlings is called a 'murmuration'.",
    "Cuttlefish have three hearts and greenish-blue blood.",
    "A group of storks is called a 'mustering'.",
    "Octopuses can fit through any hole larger than their beak.",
    "A group of hawks is called a 'kettle' when flying or a 'cast' when perched.",
    "Tarantulas can live up to 30 years.",
    "A group of nightingales is called a 'watch'.",
    "Jellyfish have been around for 650 million years - before dinosaurs and trees!",
    "A group of doves is called a 'dule' or 'pitying'.",

    // History Facts (50)
    "Cleopatra lived closer to the Moon landing than to the building of the Great Pyramid.",
    "Oxford University is older than the Aztec Empire. Oxford started in 1096, Aztecs in 1428.",
    "The last woolly mammoth died in 2000 BC - 1,000 years after the pyramids were built!",
    "Nintendo was founded in 1889 as a playing card company.",
    "The Great Wall of China is NOT visible from space with the naked eye.",
    "Ancient Romans used urine as mouthwash (the ammonia whitened teeth).",
    "Forks weren't used in Europe until the 11th century - people ate with their hands.",
    "The shortest war in history lasted 38 minutes (Anglo-Zanzibar War, 1896).",
    "Napoleon wasn't actually short - at 5'7\", he was average height for his time.",
    "Ancient Egyptians slept on pillows made of stone.",
    "Vikings didn't wear horned helmets - that's a myth from opera costumes.",
    "The earliest recorded joke (1900 BC) was a fart joke.",
    "Ketchup was sold as medicine in the 1830s.",
    "The Eiffel Tower can grow 6 inches in summer due to thermal expansion.",
    "Hitler was nominated for the Nobel Peace Prize in 1939.",
    "Ancient Romans used to clean themselves with a shared sponge on a stick.",
    "Julius Caesar was kidnapped by pirates who demanded a ransom. He laughed and said he was worth more.",
    "The Leaning Tower of Pisa has never been straight.",
    "Ancient Greeks exercised naked - the word 'gymnasium' comes from 'gymnos' (naked).",
    "The first programmable computer weighed 27 tons (ENIAC, 1945).",
    "People used to mail children through the postal service in the early 1900s.",
    "The Ancient Olympics banned women from competing - or even watching.",
    "Benjamin Franklin never patented any of his inventions.",
    "The inventor of the Pringles can is buried in one.",
    "The first alarm clock could only ring at 4 am.",
    "Ancient Egyptians invented toothpaste 5,000 years ago.",
    "The first webcam was invented to watch a coffee pot at Cambridge University.",
    "In Ancient Rome, a commoner's dinner was bread dipped in wine.",
    "The oldest 'your mom' joke dates back to 3,500 BC in ancient Babylon.",
    "Ancient Egyptians wore makeup - both men and women used eyeliner.",
    "The Great Fire of London (1666) killed only 6 people officially.",
    "Thomas Edison didn't invent the light bulb - he improved it.",
    "The first telephone book had only 50 names and no phone numbers.",
    "Ancient Romans paid taxes in honey because it was so valuable.",
    "The French Revolution started in 1789, the same year the US Constitution was ratified.",
    "George Washington grew hemp but not marijuana.",
    "The bicycle was invented before the car.",
    "Sliced bread was invented in 1928.",
    "The first computer virus was created in 1983.",
    "Ancient Egyptians believed cats were sacred and mummified them.",
    "Shakespeare invented over 1,700 English words.",
    "The oldest known musical instrument is a 40,000-year-old flute made from bird bone.",
    "Ancient Romans had heated floors and running water.",
    "The first vending machine was invented in 1st century AD - it dispensed holy water.",
    "Abraham Lincoln is in the Wrestling Hall of Fame - he lost only 1 out of 300 matches.",
    "Ancient Mayans used chocolate as currency.",
    "The Colosseum could be filled or drained of water for mock sea battles.",
    "Queen Elizabeth II served in World War II as a mechanic and driver.",
    "The ice age ended only 12,000 years ago - humans existed throughout it!",
    "Ancient Greeks believed redheads turned into vampires after death.",

    // Technology & Modern Facts (50)
    "The first computer bug was an actual bug - a moth found in a computer in 1947.",
    "Your smartphone has more computing power than all of NASA in 1969 for the Moon landing.",
    "The first email was sent in 1971, and the @ symbol was chosen because it didn't appear in names.",
    "Nintendo's Game Boy had less computing power than a modern calculator.",
    "The first YouTube video was uploaded on April 23, 2005, titled 'Me at the zoo'.",
    "The first camera took 8 hours to take a single photo.",
    "The first computer mouse was made of wood.",
    "WiFi doesn't stand for anything - it's just a made-up marketing term.",
    "The first domain name ever registered was Symbolics.com in 1985.",
    "Google's first server rack was built from LEGO bricks.",
    "The average person unlocks their phone 150 times per day.",
    "Nokia used to make toilet paper before phones.",
    "The first webcam was used to monitor a coffee pot.",
    "The word 'robot' comes from Czech word 'robota' meaning forced labor.",
    "USB flash drives were invented in 1999.",
    "The first iPhone didn't have copy-paste or a video camera.",
    "Amazon was originally going to be called 'Cadabra'.",
    "The first computer weighed more than 27 tons.",
    "Bluetooth is named after a 10th-century Scandinavian king, Harald Bluetooth.",
    "The first website is still online - info.cern.ch.",
    "Humans didn't evolve to work 8 hours straight - it was an industrial revolution invention.",
    "The average smartphone has more processing power than a supercomputer from 1985.",
    "The first ever tweet was sent on March 21, 2006.",
    "The computer in your car is more powerful than the computers that landed astronauts on the Moon.",
    "The first banner ad on the internet had a 44% click rate (now it's less than 0.1%).",
    "PayPal was originally designed to send money between PalmPilots.",
    "The first CD pressed in the US was Bruce Springsteen's 'Born in the USA'.",
    "MP3 files delete sounds humans can't hear to save space.",
    "The first video game console was released in 1972 - the Magnavox Odyssey.",
    "Facebook's blue color scheme was chosen because Mark Zuckerberg is red-green colorblind.",
    "The first computer programmer was a woman - Ada Lovelace in the 1840s.",
    "YouTube's original purpose was as a dating site.",
    "The average person spends 7 years of their life on the internet.",
    "Social media addiction activates the same brain areas as drug addiction.",
    "Tesla cars have a 'dog mode' that keeps the AC on for pets.",
    "The first laptop (Osborne 1) weighed 24 pounds.",
    "QR codes were invented in 1994 to track automotive parts.",
    "The word 'meme' was coined in 1976, decades before internet memes.",
    "Linux is free and open source - it runs most of the internet's servers.",
    "The first hard drive (1956) was the size of a refrigerator and held 5 MB.",
    "Apple's first logo featured Isaac Newton sitting under an apple tree.",
    "The first iPod could hold 1,000 songs - now phones hold millions.",
    "Emails were around before the World Wide Web.",
    "The first GIF ever made was of a plane - created in 1987.",
    "Ctrl+Alt+Delete was supposed to be used rarely but became standard.",
    "The first commercially available mobile phone weighed 2 pounds.",
    "Spotify has over 70 million songs - it would take 270+ years to listen to all of them.",
    "The Mars Rover runs on solar panels and is controlled with 15-minute delay.",
    "3D printing can now print human organs using bio-ink.",
    "Self-driving cars have already driven over 20 million miles on public roads.",

    "You can't hum while holding your nose closed. Try it!",
    "If you shuffle a deck of cards, the order has probably never existed before in history.",
    "Your skeleton is wet inside your body right now. Think about that.",
    "Time moves slower at higher altitudes due to gravity. Mountain climbers age faster!",
    "The probability of being born is about 1 in 400 trillion.",
    "You've never seen your face in person - only reflections and photos.",
    "You are younger than you think - parts of your body are only a few weeks old.",
    "The voices you hear in your head when reading are unique to you.",
    "You can see your nose all the time, but your brain ignores it.",
    "No piece of paper can be folded in half more than 7-8 times (try it!).",
    "The word 'swims' upside down is still 'swims'.",
    "The hashtag symbol (#) is called an octothorpe.",
    "You can't lick your elbow (90% of people try after reading this).",
    "Your tongue can't find a comfortable place to rest in your mouth once you think about it.",
    "You're now breathing manually. You're welcome.",
    "Thinking about your breathing makes it harder to breathe naturally.",
    "You can't stand backwards on stairs.",
    "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter of the alphabet.",
    "You read 'WTF' in your head differently than 'What the f***'.",
    "Right now, you're the oldest you've ever been and the youngest you'll ever be again.",
    "Technically, going to bed is just traveling 8 hours into the future.",
    "Your teeth are the only part of your skeleton you clean daily.",
    "Brushing your teeth is the only time you clean your skeleton.",
    "We put a man on the Moon before we put wheels on luggage.",
    "Someone out there has your dream job right now.",
    "Every photo of you is from when you were younger.",
    "Technically, your brain named itself.",
    "You've never been in an empty room - the air counts as something.",
    "The smell of freshly cut grass is actually a plant distress signal.",
    "Somewhere in the world, someone just started reading this exact fact at the same time as you.",
    "You will never experience total sensory deprivation - you can always hear your heartbeat and feel your breathing.",
    "Somewhere, there's a picture of you that you'll never see.",
    "Your parents carried you before you were born and will carry your memory after they're gone.",
    "Every person you've ever met knows a version of you that you've never met.",
    "There are people alive today who will live to see the year 2100.",
    "You share your birthday with approximately 20 million other people.",
    "At this very moment, someone is doing something for the last time in their life.",
    "Somewhere, someone is thinking about you right now.",
    "You'll never know if you've ever been in someone's dream.",
    "At some point, your parents put you down and never picked you up again.",
    "The first person to walk on Mars is alive right now somewhere on Earth.",
    "You've walked past hundreds of people who are now dead without knowing it.",
    "Your future self is watching you right now through memories.",
    "There's a date you'll die on, you just don't know when.",
    "Right now is the oldest the universe has ever been and the youngest it will ever be again.",
    "Someone out there remembers you randomly and smiles.",
    "You've survived 100% of your worst days so far.",
    "The next person you meet could become the most important person in your life.",
    "Somewhere, a tree is growing that will eventually be made into your coffin.",
    "You've probably forgotten more moments of your life than you remember.",
    "The scientific term for brain freeze is 'sphenopalatine ganglioneuralgia'.",
    "Canadians say 'sorry' so often that a 2009 law declared apologies can't be used as proof of guilt.",
    "When dinosaurs lived on Earth, volcanoes were erupting on the Moon.",
    "The only letters not on the periodic table are J and Q.",
    "A Polar Bear and Grizzly Bear hybrid is called a 'pizzly bear'.",
    "In 2006, Pepsi alerted Coca-Cola after being offered their secret formula.",
    "All ten of the highest mountain peaks in the U.S. are in Alaska.",
    "Nintendo trademarked the phrase 'It's on like Donkey Kong' in 2010.",
    "Daniel Radcliffe was allergic to his Harry Potter glasses, so they were swapped for hypoallergenic ones.",
    "The 'I'm king of the world!' line in Titanic was improvised by Leonardo DiCaprio.",
    "A single strand of spaghetti is called a 'spaghetto'.",
    "Hershey's Kisses are named after the sound they make when dropped onto the conveyor belt.",
    "Princess Peach couldn't move in early games due to technical limitations.",
    "Leaving a party without saying goodbye is called a 'French exit' in English and 'to leave like the English' in French.",
    "Cutting down a saguaro cactus in Arizona can result in felony charges.",
    "Colorado has an active volcano that last erupted around the time the pyramids were built.",
    "Snow White was the first film to release a motion-picture soundtrack.",
    "Pointing your car key to your head can increase its signal range slightly.",
    "Fruit stickers are edible and use FDA-approved adhesive.",
    "The scientific name for the giant anteater means 'ant eating with three fingers'.",
    "Astronaut literally means 'star sailor' in Greek.",
    "The flashes you see when rubbing your eyes are called 'phosphenes'.",
    "Baby pandas are smaller than mice at birth.",
    "Iceland has no railway system.",
    "The largest known prime number has over 24 million digits.",
    "A treasure worth over 1 million dollars hidden in the Rockies was found in 2020.",
    "The lead singer of The Offspring earned a PhD in molecular biology.",
    "The world's largest grand piano was built by a 15-year-old in New Zealand.",
    "The tongue is the only muscle attached at just one end.",
    "Japan has schools dedicated to teaching people how to be funny.",
    "There are more LEGO minifigures than people on Earth.",
    "Bagheera kiplingi is the only known vegetarian spider.",
    "In Metal Gear Solid 3, a boss can be defeated by waiting a week in real time.",
    "The Roman-Persian wars lasted over 680 years.",
    "Elvis Presley was naturally blonde.",
    "The name 'Jesus' is derived through multiple translations from Hebrew.",
    "Ed Sheeran was discovered by Jamie Foxx after moving to LA.",
    "German Chocolate Cake is named after a person, not the country.",
    "Service animals were first formally used during World War I.",
    "An 11-year-old suggested the name Pluto.",
    "The voice actors for SpongeBob and Karen are married in real life.",
    "About 50% of all gold ever mined came from one area in South Africa.",
    "75% of the world's food comes from just 12 plants and 5 animal species.",
    "Star Wars originally released in only 32 theaters.",
    "The slogan 'Keep Calm and Carry On' was created during WWII but used decades later.",
    "Apple once paid 1.7 million dollars for land worth far less to build a data center.",
    "Tirana is one of the few capitals without a McDonald's.",
    "Swedish Fish and red Sour Patch Kids are essentially the same candy.",
    "Brazil has the largest Japanese population outside Japan.",
    "IKEA stands for the founder's name, farm, and hometown.",
    "Stephen Hawking hosted a party for time travelers—no one showed up.",
    "Violin bows are typically made from horsehair.",
    "Johnny Cash was told to stop taking voice lessons after just three sessions.",
    "There is an island called 'Just Enough Room' with space for one house and one tree.",
    "A medieval 'moment' lasted about 90 seconds.",
    "The Flintstones was the first animated primetime TV show.",
    "Some mirrors are designed to make people look thinner, boosting store sales.",
    "Dr Pepper has no period in its name.",
    "Underwater rugby is a real sport played in pools.",
    "Standing burns about 114 calories per hour for a 150-pound person.",
    "GPS costs about 2 million dollars per day to operate.",
    "In WWII, fake money was dropped over Britain to destabilize the economy.",
    "A candle flame could be visible from 30 miles away in perfect darkness.",
    "Bulls are colorblind and not angered by red.",
    "A punctuation mark for sarcasm exists: ⸮",
    "Lettuce is part of the sunflower family.",
    "Flossing may improve memory by improving blood flow.",
    "A bunch of bananas is called a 'hand'; one banana is a 'finger'.",
    "The Hobbit originally had a different version of Gollum's ring scene.",
    "Texas had no official flag for over 50 years.",
    "A woodchuck could chuck about 700 pounds of wood, theoretically.",
    "Red Solo cups are popular souvenirs outside the U.S.",
    "Swedish meatballs were inspired by a Turkish recipe.",
    "Saint Lucia is the only country named after a woman.",
    "Cats have 'ear furnishings' to help block dirt and improve hearing.",
    "Sharks have been found living inside underwater volcanoes.",
    "Sometimes Pluto is closer to the Sun than Neptune.",
    "A town in Nebraska has only one resident, who is also the mayor.",
    "Ethiopia's calendar is about 7.5 years behind the Gregorian calendar.",
    "PNG files were created after GIF licensing issues.",
    "China built panda-shaped solar farms to attract interest in renewable energy.",
    "Mercury and Venus are the only planets with no moons.",
    "The average child receives about 3.70 dollars per tooth from the tooth fairy.",
    "English adjectives follow a specific order: quantity, value, size, temperature, age, shape, color, origin, material.",
    "The first motel opened in 1925 for 1.25 dollars per night.",
    "Scotland resisted Roman conquest.",
    "Mount Rushmore cost less than 1 million dollars to build.",
    "Samsung means 'three stars' in Korean.",
    "Geckos eat their shed skin to avoid predators.",
    "Bees have knees used to collect pollen.",
    "The Korean DMZ has become a wildlife haven.",
    "Walt Disney got the idea for Disneyland while watching a carousel.",
    "There is a tartan pattern designed for Mars exploration.",
    "Santa Claus was issued a U.S. pilot's license in 1927.",
    "When you lose fat, most of it is exhaled as carbon dioxide.",
    "Velociraptor means 'swift thief' in Latin.",
    "The largest stadium in the world is in North Korea.",
    "Adult cats meow only to communicate with humans.",
    "There are more possible card deck combinations than atoms in the universe.",
    "There is a UAE territory inside Oman, which itself is inside the UAE.",
    "Disappointment Island is home to over 65,000 albatross pairs.",
    "Gilligan's Island never revealed Gilligan's full name.",
    "Video games have been shown to help reduce depression symptoms."
    "Bi-weekly has two meanings: twice a week or once every two weeks.""The Mona Lisa was stolen in 1911, drawing more visitors to the empty space than the painting.""Insurance policies for alien abduction have been sold to around 50,000 people.""Volvo invented the three-point seatbelt and made it free for everyone to use.""In 2005, Connecticut accidentally sent an evacuation alert to the entire state.""An 18-year-old played the 8-year-old Grinch in The Grinch (2000).""Rebecca Felton served as a U.S. Senator for just one day.""Webster’s Dictionary accidentally included the fake word 'Dord' for five years.""Amber rear turn signals can reduce crashes by about 28%.""A guide dog named Roselle led her owner down 78 floors during 9/11 safely.""In Russia, some believe eating ice cream helps keep you warm.""A hidden South Park episode caused a recall of Tiger Woods 99.""Giant lemurs in Madagascar were once as big as gorillas.""Over a million people live in underground bunkers beneath Beijing.""Chuck E. Cheese’s full name is Charles Entertainment Cheese.""All roulette wheel numbers add up to 666.""Plumbers call the day after Thanksgiving 'Brown Friday' due to heavy workload.""The wife of actor Anthony Perkins died on one of the 9/11 planes.""The thumbs-up gesture may have originated with Chinese pilots.""Toy Story 2 replaced the American flag with a globe in some countries.""Olympus Mons is three times taller than Mount Everest.""Batman and Predator share the same comic universe.""Loneliness can be as harmful as smoking, according to studies.""You can get a driver's permit at age 14 in South Dakota.""The Backpack Kid’s real name is Russell Horning.""Adidas made over a million shoes from ocean plastic in 2017.""The British pound is over 1,200 years old.""The bumblebee bat is the smallest mammal by weight.""The Itchy & Scratchy Show has over 100 fictional episodes.""Will Smith nearly went bankrupt before The Fresh Prince of Bel-Air.""The Great Pyramid of Giza has eight sides.""English was brought to Britain by Germanic settlers.""Humans are born with only two fears: loud sounds and falling.""The Sapsali dog in Korea was believed to ward off evil spirits.""Qantas once powered a flight using cooking oil biofuel.""Bananas and pumpkins are botanically classified as berries.""One horse can produce around 15 horsepower.""The Leaning Tower of Pisa tilts due to soft ground.""The Eiffel Tower’s paint weighs as much as ten elephants.""FBI agents must visit the Holocaust Museum during training.""Dinosaurs lived on every continent, including Antarctica.""A blue whale’s heart is the size of a small car.""The red cross symbol is based on the Swiss flag.""Slavery was only officially abolished in Mauritania in 2007.""A man named Ronald MacDonald once robbed a Wendy’s.""England and Portugal have the oldest alliance since 1386.""Harry Potter was rejected by 12 publishers before success.""'Shotgun wedding' in Japanese translates to 'oops-we-did-it marriage'.""Garlic can attract leeches.""28,000 rubber ducks lost at sea traveled the world for years.""Caller ID usage tripled after the movie Scream.""A plane crash occurred after a pilot let his kids control the plane.""Uranus takes 84 years to orbit the Sun.""A 26-sided shape is called a rhombicuboctahedron.""A mob boss pretended insanity by wandering in a bathrobe.""Silly string has been used by the military to detect tripwires.""It’s very difficult to break an egg by squeezing it evenly.""Smallpox and rinderpest are the only diseases eradicated globally.""A deep-sea snail has armor strong enough to inspire military design.""There are over 6,000 types of grass.""The Earth's atmosphere weighs about 11 quintillion pounds.""'Time anxiety' is the fear of being late.""Ant queens can live up to 30 years.""Researchers once predicted Facebook would lose most users by 2017.""Orlando Bloom reportedly has a fear of pigs.""Most of the world’s largest statues are of Buddha.""Meghan Trainor has a fear of the dark.""The largest wave ever surfed was 78 feet tall.""Red Bull’s logo features a gaur, not bulls.""Beer is transported through underground pipelines in Bruges.""A group of lemurs is called a 'conspiracy'.""Primark originally opened as Penney’s in Ireland.""Ron Swanson was inspired by a real government worker.""There are more captive tigers in the U.S. than wild ones worldwide.""London Bridge was relocated to Arizona.""Scrappy-Doo disappeared due to fan dislike.""The first X-rated animated film was Fritz the Cat.""About one-third of cats are unaffected by catnip.""Facebook tracks user activity across the web.""Bubble wrap was originally intended as wallpaper.""A cricket match once lasted over 12 days.""MIT offers most course materials online for free.""Einstein mastered calculus by age 15.""Madagascar was named due to a misspelling.""An asteroid is named after Tom Hanks.""The EU flag’s stars were chosen for symbolism, not meaning.""High heels were once worn by children.""Elephants may perceive humans as cute.""Blue-eyed cats are more likely to be deaf.""The Guinness World Records began from a bar argument.""Barry Manilow wrote famous advertising jingles.""Magpies can recognize themselves in mirrors.""A fake typhus outbreak saved 8,000 lives in WWII.""Zinc’s atomic number is 30.""A chef’s hat is called a toque.""TSA has a high failure rate in security tests.""Americans own an average of seven pairs of jeans.""Charles Dickens slept facing north for creativity.""Shawn Mendes reached #1 on iTunes in 37 minutes.""The U.S. has gained forest land since 1990.""Perfluorohexane allows animals to breathe liquid.""Curry can reduce methane emissions in sheep.""Conversations have near-universal timing patterns.""Cold showers may improve circulation and mood.""Mongolia has a navy with one boat.""German soldiers once believed camel droppings brought luck.""In Alabama, some Sunday activities are illegal.""Bumper cars were originally meant to avoid collisions.""A woman was elected before women could vote nationally.""Dutch Sesame Street has a character named Pino.""The Bible has been translated into over 3,000 languages.""Buzz Aldrin voiced a character in Mass Effect 3.""The first July 4th celebration was in 1777.""Justin Bieber’s first tweet was in 2009.""Dinosaurs may have shed skin like reptiles.""Zebras have one toe per foot.""Dentistry dates back to 7000 BC.""Vulpix was originally going to be called FoxFire.""The first feature film was made in 1906.""Roman surgeons trained to ignore screams.""William Hung is a descendant of Confucius.""A chimpanzee co-host boosted TV ratings in the 1950s.""Snow qualifies as a mineral, but water does not.""Only one Blockbuster store remains.""There is a geocache on the ISS.""Mozart recreated secret music from memory at age 14.""Canada consumes the most mac and cheese.""Female octopuses may eat males after mating.""Scotland attempted to recreate the Parthenon.""John Quincy Adams kept a pet alligator in the White House.""The U.S. bought Alaska for 7.2 million dollars.""McDonald’s in the Philippines serves spaghetti.""Pepperoni is an American invention.""Pumpkins are related to cucumbers.""Prime numbers squared minus one are divisible by 24.""Puppies are born blind and deaf.""Pizza Margherita represents the Italian flag.""Sudan has more pyramids than Egypt.""The Statue of Liberty was funded by donations.""Some hamsters can grow up to 13 inches long.""Hollywood handprints started by accident.""Snakes can sense earthquakes days in advance.""Soviets built nuclear-powered lighthouses.""Animals with larger brains yawn longer.""Siri was originally planned as an app.""Some babies are born with teeth.""A Minnesota town has over 20 zip codes.""The USDA defines a sandwich by meat and bread percentages.""Nutella was created during WWII chocolate shortages.""Xbox was originally called DirectXbox.""It’s illegal to own one guinea pig in Switzerland.""The safety pin was invented in 1849.""A woman survived a 33,000 ft fall without a parachute.""A ladder in Jerusalem cannot be moved due to religious agreement.""Eminem’s mom sued him and settled for 25,000 dollars.""San Marino is one of the smallest countries in the world.""A woman faked a 9/11 tragedy and led a support group.""The band name 'Postal Service' came from mailing music.""December 3rd is 'Roof Over Your Head Day'.""Alaska can be typed on one keyboard row.""Michael Jackson’s glove was a modified golf glove.""Spiked dog collars were invented to fight wolves.""'Mr.' and 'Mrs.' come from 'master' and 'mistress'.""Kosher salt is used to remove blood from meat.""Q-Tips were originally called Baby Gays.""Last pure gold Olympic medals were awarded in 1912.""Your skeleton renews itself every 10 years.""Starcraft was the first game played in space.""Houston is the most diverse U.S. city.""Putting a pillow on your fridge is a holiday tradition.""Water expands by 9% when frozen.""The paper strip in Hershey’s Kisses has a name.""Jet Li declined being Nixon’s bodyguard.""Grapefruit affects many medications.""Dinosaurs swallowed rocks to digest food.""Sliced bread was briefly banned in 1943.""Lincoln loved cats and fed them at dinner.""Canada’s independence timeline is debated.""NASA once pranked finding water on Mars.""There’s a town named Hooker with a humorous slogan.""Japan has a shortage of trained ninjas.""New Jersey had four governors in eight days.""Mad Max and Happy Feet share a creator.""Gamers perform better in surgery tasks.""It’s illegal to die in Svalbard.""Cellophane was made to protect tablecloths.""Crows are being trained to clean up cigarette butts.""Hunger can affect mood due to low glucose.""A cat served as mayor in Alaska.""Spam got its name from a comedy sketch.""Forward-facing eyes help humans see in 3D.""The Pringles inventor was buried in a can.""QR codes can be used on gravestones.""Jim Carrey’s chipped tooth is real.""Ginger beer is fermented, ginger ale is not.""Steve Jobs swapped phones during the first iPhone demo.""Dine-and-dash laws vary by state.""NYPD monitored Andre the Giant while drinking.""The word 'mafia' is never said in The Godfather."
     "There are more LEGO minifigures than people on Earth.",
    "Bagheera kiplingi is the only known vegetarian spider.",
    "In Metal Gear Solid 3, a boss can be defeated by waiting a week in real time.",
    "The only window that opens on the presidential car is the driver’s window to pay tolls. It also has no keyholes, and only the Secret Service knows how to open the doors.",
    "Thomas Edison invented an electric pen in 1876 that was later adapted to become the first tattoo machine in 1891.",
    "Animal Planet aired two fake documentaries that 'proved' mermaids exist. So many people thought it was real that the U.S. government issued an official statement about it.",
    "In 18th-century England, having a pineapple was a symbol of wealth because of high import duties. They would be used as displays rather than eaten.",
    "Marvel’s Deadpool issue #27 holds the Guinness World Record for the most comic book characters on one cover.",
    "Instead of an agent, Bill Murray uses a 1-800 number where you can leave a message if you want to cast him in a movie or event.",
    "When written down, the word 'almost' is the longest word in the English language to have all of its letters in alphabetical order.",
    "The black-footed cat is the smallest wild cat, at just 20 inches long.",
    "The world’s most remote ATM is run by Wells Fargo in the Antarctic.",
    "The first Game Boy could run for a staggering 30 hours on only two AA batteries!",
    "Hershey’s chocolate syrup, Ritz Crackers, DumDums, and Oreos are all suitable for vegans.",
    "The sound of a Star Wars lightsaber was created by combining the idle hum of a film projector with the buzz of an old TV set.",
    "Your tonsils can grow back if any tissue is left behind during the removal process.",
    "Greenland voted to leave the European Union in 1985 and has not rejoined since.",
    "Every second, the human eye moves about 50 times.",
    "Only 2% of the world’s population has green eyes.",
    "The A.D. and B.C. system was not proposed until 525 A.D.",
    "Daniel Radcliffe had the same stunt double for the first six Harry Potter movies.",
    "'Tater Tots' originally failed because people thought they were too cheap.",
    "Movie theaters make roughly 85% of their profit from concession stands.",
    "Honey can preserve food for centuries.",
    "The odds of being born on February 29th are 1 in 1461.",
    "People who donate blood in Sweden get a text when it saves a life.",
    "In the U.S., around ¾ of houses have peanut butter.",
    "The average U.S. household has 300,000 items.",
    "Motel 6 and Super 8 got their names from room prices.",
    "About 25% of blood from the heart goes to the kidneys.",
    "In Israel, it is illegal to bring bears to the beach.",
    "Comets reflect only 4% of light.",
    "The shape of Pringles is called a hyperbolic paraboloid.",
    "The highest film body count is in Lord of the Rings: Return of the King.",
    "There is an island in the Bahamas populated by pigs.",
    "The German Autobahn has no general speed limit.",
    "If you only ate rabbit, you could die from protein poisoning.",
    "Every Pixar movie references the next one.",
    "Red pandas have no close relatives.",
    "The first computer mouse was made of wood.",
    "Venus is hotter than Mercury.",
    "It snowed in the Sahara in 1979.",
    "PewDiePie once sold hot dogs to support himself.",
    "About 1,000,000 dogs in the U.S. are heirs in wills.",
    "Sweden has the most islands in the world.",
    "George Washington was honored by Napoleon.",
    "Tony Blair was the first leader with a YouTube channel.",
    "Double rainbows have reversed colors.",
    "Bookworms are real insects.",
    "Russia has the most satellites in orbit.",
    "The most complex Chinese character has 62 strokes.",
    "It is illegal to flush a toilet after 10 pm in Switzerland.",
    "A group of rhinos is called a crash.",
    "A snail once stayed alive glued to a museum card for 4 years.",
    "William Shakespeare put a curse on his tombstone.",
    "Cookie Monster’s real name is Sid.",
    "There are 1,800 thunderstorms happening at any time.",
    "The largest living thing is a giant sequoia tree.",
    "1089 × 9 = 9801.",
    "Saturn could fit Earth 755 times.",
    "'Rap God' has 1,560 words.",
    "Three dogs survived the Titanic.",
    "China has 3,000 miles of missile tunnels.",
    "Pitbulls are naturally affectionate dogs.",
    "Using tanning beds before 30 raises melanoma risk by 75%.",
    "Owls can fly silently due to special feathers.",
    "A man grounded 4,000 planes on 9/11 on his first day.",
    "Your brain uses 20% of your oxygen.",
    "The Eiffel Tower was almost built in Barcelona.",
    "The longest place name has 85 letters.",
    "Kangaroos grow until they die.",
    "A red blood cell circulates your body in 20 seconds.",
    "A 30-sided shape is a triacontagon.",
    "A waitress once got 3 million dollars as a tip.",
    "Penguins live safely near landmines in the Falklands.",
    "The first jet aircraft was made in Nazi Germany.",
    "Early photos required 8 hours of stillness.",
    "19 of the 20 most-watched U.S. broadcasts are Super Bowls.",
    "A snail can sleep for 3 years.",
    "David Bowie launched an internet provider.",
    "The Memphis Pyramid is a Bass Pro Shop.",
    "Females distinguish colors better; males track motion better.",
    "The average beehive matches human body temperature.",
    "The Lacoste logo was the first designer logo.",
    "Neptune’s day is about 16 hours long.",
    "The fear of vegetables is called lachanophobia.",
    "Twelve is the largest one-syllable number.",
    "The Kakapo is the only flightless parrot.",
    "Dogs with longer faces tend to live longer.",
    "The human heart beats about 3.6 million times a year.",
    "A jar of honey takes 864 bees to make.",
    "7% of Americans think chocolate milk comes from brown cows.",
    "In Japan, KFC is a popular Christmas meal.",
    "Jupiter orbits the Sun every 11.86 years.",
    "Hands-free driving can be as dangerous as drunk driving.",
    "A scorpion can sting itself to death if exposed to alcohol.",
    "The first roller coaster transported coal.",
    "The monster in Frankenstein was never named."
     "There are more LEGO minifigures than people on Earth.",
    "Bagheera kiplingi is the only known vegetarian spider.",
    "In Metal Gear Solid 3, a boss can be defeated by waiting a week in real time.",
    "At one point, 50% of the CDs produced worldwide had an AOL logo on them.",
    "There are 30 times more trees on Earth than stars in the Milky Way.",
    "The first spacecraft to visit Mars was Mariner 4 in 1965.",
    "Jesus was likely born in a cave, not a stable, according to some scholars.",
    "The browning of toast is called the Maillard Reaction.",
    "Cats have five toes on their front paws but only four on their back paws.",
    "The word 'barbarian' came from Greeks mimicking foreign speech as 'bar bar bar'.",
    "Horses take turns staying awake to watch for danger.",
    "Antimatter is the most expensive substance on Earth.",
    "The word 'friends' is said in every episode of Friends.",
    "Chess and Sudoku both help improve memory and thinking.",
    "In Utah, birds have the right of way on highways.",
    "Logan was the most complained-about movie in the UK in 2017.",
    "Nicolas Cage encouraged Johnny Depp to pursue acting.",
    "Stoats hypnotize prey by jumping and spinning.",
    "Some jellyfish are biologically immortal.",
    "Extreme ironing is a real sport.",
    "Mickey Mouse first spoke in 1929 saying 'Hot dogs!'",
    "Bob Ross had naturally straight hair but permed it for cost reasons.",
    "Longer dating before marriage lowers divorce risk.",
    "A Central Park Zoo hot dog cart permit costs about 290,000 dollars per year.",
    "About 15% of Twitter accounts are bots.",
    "Only about 45% of the London Underground is underground.",
    "The TomTato plant grows tomatoes and potatoes together.",
    "'Jayus' means a joke so bad it's funny in Indonesian.",
    "Dog ownership is higher in red states, cats in blue states.",
    "Frederick Douglass was the most photographed man of the 1800s.",
    "Fruit seeds like apple seeds contain small amounts of cyanide.",
    "Australia has nearly twice as many kangaroos as people.",
    "During Prohibition, whiskey could be sold in pharmacies.",
    "About 15% of iPhone users have cracked screens.",
    "Baby owls are called owlets.",
    "EU banknotes feature fictional architecture.",
    "Elephants can die from heartbreak.",
    "It takes about 12 seconds to count to 24.",
    "Australia has 'Democracy Sausages' on election day.",
    "Alicia Keys learned cello in 4 weeks for a movie role.",
    "Jamie Oliver didn’t read his first novel until age 38.",
    "Uncle Phil also voiced Shredder in TMNT.",
    "The fear of cooking is called Mageirocophobia.",
    "Rats in Cambodia are trained to detect landmines.",
    "About 10% of Filipinos live abroad.",
    "A group of unicorns is called a blessing.",
    "Ulysses S. Grant was arrested for speeding on a horse.",
    "Paddington Bear has two birthdays.",
    "Dogs have 42 teeth as adults.",
    "Cigarette filters were originally made from cork.",
    "Killer whales once cooperated with humans in whaling.",
    "Some fighter pilots on 9/11 had no live ammo.",
    "Norwegian prisons encourage guards to bond with inmates.",
    "Denmark’s flag is the oldest still in use.",
    "The world’s population could fit inside Texas.",
    "97 chickens are killed every 0.05 seconds globally.",
    "Michael Emerson became a Lost regular after 3 planned episodes.",
    "Paul McCartney was paid £1 for the 2012 Olympics performance.",
    "Mister Rogers’ sweaters were knit by his mother.",
    "Monster Energy limits differ by country.",
    "Coca-Cola now sells over 19,000 drinks per second.",
    "Hamilton was shot at the same place his son died.",
    "Sunflowers can help remove radiation from soil.",
    "Medical errors are a leading cause of death in the US.",
    "Nicki Minaj is afraid of heights.",
    "Ed Sheeran has a ketchup tattoo.",
    "Guides exist for observing Ramadan in space.",
    "Manatees can get frostbite in cold water.",
    "There is a town named Santa Claus in Indiana.",
    "'Darth Vader' means 'Dark Father' in Dutch.",
    "Chocolate syrup was used as blood in Psycho.",
    "Mars has more storms when closer to the Sun.",
    "False eyelashes were first made using human hair.",
    "'Gymnastics' means 'to train naked' in Greek.",
    "All Clone Troopers in Episode III were CGI.",
    "Swearing is not allowed at Wimbledon.",
    "It’s illegal to play music just to annoy people in parts of Australia.",
    "Bob Marley’s last words were 'Money can’t buy life.'",
    "The US consumes nearly half the world’s chocolate.",
    "Portal 2 improves cognition better than brain-training games.",
    "Eating breakfast improves mental and physical health.",
    "The original Xbox used real Apollo mission audio.",
    "A Pink Floyd pig once shut down flights.",
    "Herring communicate via flatulence.",
    "'Schnapsidee' means a bad idea that sounds good drunk.",
    "Forgiveness is strongly linked to happiness.",
    "Police used ice cream music to calm riots in Belfast.",
    "Ralph Lauren’s real name is Ralph Lifshitz.",
    "Egypt once considered dismantling the pyramids.",
    "Pantheism views the universe itself as God.",
    "People buy Pop-Tarts and beer before hurricanes.",
    "#love is the most used Instagram hashtag.",
    "Cats can hear ultrasound.",
    "A woman survived being frozen under ice for over an hour.",
    "Aggressive sitting is a real sport.",
    "The Harry Potter series has over 1 million words.",
    "Daniel Radcliffe identifies as Jewish.",
    "Your forearm length matches your foot length.",
    "A group of parrots is called a pandemonium.",
    "PewDiePie averages millions of views per video.",
    "Jay-Z shot his brother at age 12.",
    "Throwing apples symbolized love in Ancient Greece.",
    "People blink less when using computers.",
    "Goldfish turn pale in darkness.",
    "China produces most of the world’s cucumbers.",
    "Tea bags were originally meant to be emptied.",
    "Electors once had to vote within 30 days or starve.",
    "A woman survived jumping off the Empire State Building.",
    "The Star-Spangled Banner was sewn on a brewery floor.",
    "Cucumbers can help reduce bad breath.",
    "Wonder Woman has a twin sister named Nubia.",
    "Dartmouth’s mascot includes a beer keg.",
    "27,000 trees are cut daily for toilet paper.",
    "A cloud can weigh over a million pounds.",
    "Egg yolks contain Vitamin D.",
    "Metallica played on all seven continents.",
    "November 17 is Unfriend Day.",
    "Paraguay ranked among the happiest countries.",
    "Some fireflies glow blue instead of yellow.",
    "Spacesuits take 5,000 hours to make.",
    "Over 70 mushrooms glow in the dark.",
    "Belgium holds the record for longest government formation.",
    "Skipper butterflies can fly faster than horses run.",
    "Canada requires math questions in contests.",
    "The Empire State Building was built in 410 days.",
    "Neptune was discovered through math predictions.",
    "Foxes have whiskers on their legs.",
    "Kookaburra sounds are used in jungle movies.",
    "Snow can appear blue due to light filtering.",
    "Crows can recognize human faces.",
    "A cat once disrupted a flight cockpit.",
    "May 22 is the least common birthday.",
    "Reindeer can see UV light.",
    "Angelina Jolie performed her own stunts.",
    "Shark Tank takes equity for mentions.",
    "One night on Uranus lasts 21 years.",
    "Alaska produces many serial killers.",
    "McDonald’s sells millions of pounds of fries daily.",
    "Sparta responded to threats with 'If.'",
    "Most Valentine’s cards are bought by women.",
    "Chocolate ice cream reduces pain.",
    "Patients may be conscious but paralyzed during surgery.",
    "Sharing Netflix passwords can be illegal.",
    "Volkswagen owns multiple luxury brands.",
    "Social media can increase depression.",
    "Gatorade was made for athletes.",
    "Nike was originally Blue Ribbon Sports.",
    "Nickel’s atomic number is 28.",
    "Military salutes came from lifting visors.",
    "A fire destroyed most early films in 1937.",
    "Fungi are closer to animals than plants.",
    "Bad relationships still teach lessons.",
    "France has high average sleep times.",
    "Akon leads ringtone sales globally.",
    "Einstein married his cousin.",
    "Some Pokémon share identical sounds.",
    "The Hogwarts Express is real.",
    "Einstein’s brain was stolen.",
    "Memories are reconstructed, not replayed.",
    "Liechtenstein changed its flag after duplication.",
    "Jada Pinkett Smith formed a metal band.",
    "It’s illegal to gesture offensively at cars in Zimbabwe.",
    "'Oxymoron' is itself an oxymoron.",
    "A tongue twister was about a fossil seller.",
    "Scientists don’t fully understand dinosaur mating.",
    "Nagoro village has more scarecrows than people.",
    "'Niblings' means nieces and nephews.",
    "Radcliffe broke dozens of wands on set.",
    "'Butterflies' are adrenaline responses.",
    "Millionaire insurers sued over easy questions.",
    "Jessie J’s full name is Jessica Cornish.",
    "The US has no official federal language.",
    "Trees are needed to produce oxygen for humans.",
    "The UK once outnumbered multiple countries combined.",
    "Walking uses 200 muscles.",
    "March 12 is Plant a Flower Day.",
    "Prisoner of Azkaban earned less than other HP films.",
    "Angel Food Cake recipes date to 1878.",
    "Arizona licenses last until age 65.",
    "ASOS means As Seen On Screen.",
    "Reading on screens is slower.",
    "Rabbits can die from fear.",
    "Pistanthrophobia is fear of trusting people.",
    "September 3 is Bacon Day.",
    "Parts of your brain rest while awake.",
    "Dubai has a large number of cranes.",
    "The Lion King was almost called King of the Jungle.",
    "Second-hand clothes hurt local industries in Africa.",
    "Cocoa helps prevent tooth decay.",
    "Baby rabbits are called a litter.",
    "Neil Patrick Harris kept his suits.",
    "Iceland has an anti-incest dating app.",
    "NASA stands for National Aeronautics and Space Administration.",
    "April 12 is Grilled Cheese Day.",
    "100,000 speeding tickets are issued daily in the US.",
    "Runway numbers show compass direction.",
    "Suriphobia is fear of mice.",
    "The goliath frog is the largest frog.",
    "December 12 is Ding-A-Ling Day.",
    "Venus has the most volcanoes in the solar system."
        "There are more LEGO minifigures than people on Earth.",
    "Bagheera kiplingi is the only known vegetarian spider.",
    "In Metal Gear Solid 3, a boss can be defeated by waiting a week in real time.",
    "The only window that opens on the presidential car is the driver’s window to pay tolls. It also has no keyholes, and only the Secret Service knows how to open the doors.",
    "Thomas Edison invented an electric pen in 1876 that was later adapted to become the first tattoo machine in 1891.",
    "Animal Planet aired two fake documentaries that “proved” mermaids exist. So many people thought it was real that the U.S. government issued an official statement about it.",
    "In 18th-century England, having a pineapple was a symbol of wealth because of high import duties. They would be used as displays rather than eaten.",
    "Marvel’s Deadpool issue #27 holds the Guinness World Record for the most comic book characters on one cover.",
    "Instead of an agent, Bill Murray uses a 1-800 number where you can leave a message if you want to cast him in a movie or event.",
    "When written down, the word “almost” is the longest word in the English language to have all of its letters in alphabetical order.",
    "The black-footed cat is the smallest wild cat, at just 20 inches long.",
    "The world’s most remote ATM is run by Wells Fargo in the Antarctic. The ATMs serve around 1,200 residents at the U.S. scientific facility.",
    "The first Game Boy could run for a staggering 30 hours on only two AA batteries!",
    "Hershey’s chocolate syrup, Ritz Crackers, DumDums, and Oreos are all suitable for vegans.",
    "The sound of a Star Wars lightsaber was created by combining the idle hum of a film projector with the buzz of an old TV set.",
    "Your tonsils can grow back if any tissue is left behind during the removal process.",
    "Greenland voted to leave the European Union in 1985 and has not rejoined since.",
    "Every second, the human eye moves about 50 times.",
    "Only 2% of the world’s population has green eyes.",
    "Daniel Radcliffe had the same stunt double for the first six Harry Potter movies.",
    "The average U.S. household has 300,000 things.",
    "The name for the shape of Pringles is called “Hyperbolic Paraboloid.”",
    "The highest body count in film history goes to “Lord of the Rings: Return of the King” with 836 on-screen deaths.",
    "There is an uninhabited island in the Bahamas known as Pig Beach, populated entirely by swimming pigs.",
    "Without saliva, humans are unable to taste food.",
    "Every Pixar movie contains a reference to the Pixar movie that comes after it.",
    "Doug Engelbart created the very first computer mouse from wood in 1964.",
    "The smallest thing ever photographed is the shadow of an atom.",
    "Despite Mercury being closest to the Sun, Venus is the warmest planet.",
    "In every scene of Fight Club, there is a Starbucks coffee cup.",
    "It snowed in the Sahara desert for 30 minutes on February 18, 1979.",
    "PewDiePie supported his YouTube channel by selling hot dogs.",
    "Steven Spielberg was the executive producer of The Animaniacs.",
    "Sweden has the most islands in the world, with 221,800 islands.",
    "George Washington’s death led Napoleon Bonaparte to order a ten-day mourning period in France.",
    "The first world leader to create a YouTube channel was Tony Blair.",
    "Rick Astley has his own brand of beer.",
    "Bookworms are actual insects that bore holes in books.",
    "Dinosaurs that could run on two legs are called bipeds.",
    "The most difficult Chinese character requires 62 strokes to write.",
    "In Switzerland, it is illegal to flush the toilet after 10 pm.",
    "A group of rhinoceroses is called a crash.",
    "William Shakespeare had a curse engraved on his tombstone.",
    "Cookie Monster’s real name is Sid.",
    "Leonard Cohen wrote around 80 verses for “Hallelujah.”",
    "The largest living thing on Earth is a giant sequoia named General Sherman.",
    "Tupac had an album reach #1 while still in prison.",
    "Saturn is so large Earth could fit into it 755 times.",
    "Eminem’s “Rap God” contains 1,560 words.",
    "There is a scientist who insured her taste buds for £1 million.",
    "China has underground tunnels stretching 3,000 miles.",
    "Owls can fly silently due to specialized feathers.",
    "Snoop Dogg’s real name is Cordozar Calvin Broadus Jr.",
    "The Eiffel Tower was originally planned for Barcelona.",
    "The oldest “your mom” joke dates back 3,500 years.",
    "Kangaroos keep growing until they die.",
    "A red blood cell takes about 20 seconds to travel the body.",
    "A polygon with 30 sides is called a triacontagon.",
    "A snail can sleep for 3 years.",
    "The NBA was founded in 1946.",
    "The Hogwarts Express is a real train in Scotland.",
    "Einstein’s brain was stolen and hidden for years after his death.",
    "There is no official language of the United States at the federal level.",
    "Walking uses about 200 muscles.",
    "NASA stands for National Aeronautics and Space Administration.",
    "Airport runway numbers indicate compass direction.",
    "The goliath frog is the largest frog in the world.",
    "There are more volcanoes on Venus than any other planet.",
    "Triskaidekaphobia is the fear of the number 13.",
    "The Great Wall of China is about 3,728 miles long.",
    "A human foot contains 26 bones.",
    "Antarctica is the only continent without turtles.",
    "Warren Buffett eats McDonald’s every morning.",
    "Disney World is one of the largest buyers of explosives in the U.S.",
    "Coca-Cola owns URLs with up to 62 h’s in “ahh.”",
    "Mountain Dew was originally made as a mixer for moonshine.",
    "Fruit flies were the first animals sent into space in 1947.",
    "Only 3% of Earth’s water is fresh.",
    "Baby horses can walk within hours of being born.",
    "A crocodile once caused a plane crash in the Congo.",
    "Sprite was created by Coca-Cola to compete with 7 Up.",
    "PayPal was once voted one of the worst business ideas.",
    "Jellyfish are considered biologically immortal.",
    "Mickey Mouse was the first cartoon character to talk.",
    "Bob Ross had naturally straight hair.",
    "Utah gives birds the right of way on highways.",
    "Stoats hypnotize rabbits while hunting.",
    "Extreme ironing is a real sport.",
    "Twitter has millions of bot accounts.",
    "The London Underground is only about 45% underground.",
    "A plant called the TomTato grows tomatoes and potatoes together.",
    "Frederick Douglass was the most photographed man of the 19th century.",
    "Elephants can die of a broken heart.",
    "Rats are trained in Cambodia to detect landmines.",
    "Paddington Bear has two birthdays.",
    "Dogs have 42 teeth.",
    "Paul McCartney was paid £1 for the 2012 Olympics closing ceremony.",
    "Coca-Cola is consumed at a rate of 19,400 drinks per second.",
    "Sunflowers can help clean radioactive soil.",
    "Nicki Minaj is afraid of heights.",
    "False eyelashes were invented in 1916.",
    "You can’t swear while playing at Wimbledon.",
    "Bob Marley’s last words were “Money can’t buy life.”",
    "Portal 2 can improve brain function.",
    "Herring communicate by farting.",
    "Cats can hear ultrasound.",
    "Crows remember human faces.",
    "A cat once attacked a pilot mid-flight.",
    "Reindeer can see ultraviolet light.",
    "McDonald’s sells around 9 million pounds of fries daily.",
    "Gatorade was created for the Florida Gators.",
    "Fungus is genetically closer to animals than plants.",
    "Einstein married his cousin.",
    "Poliwag and Ditto share the same sound in Pokémon.",
    "People read about 10% slower on screens than paper.",
    "Rabbits can be scared to death.",
    "Iceland has an app to avoid dating relatives.",
    "More than 100,000 speeding tickets are issued daily in the U.S.",
    "The goliath frog can weigh up to 7.2 pounds.",
    "Neptune was discovered through math predictions.",
    "Crows can hold grudges.",
    "A passenger’s cat once caused a plane emergency.",
    "Uranus has nights that last 21 years.",
    "Facebook can negatively affect mental health.",
    "Volkswagen owns multiple luxury brands.",
    "Nickel has atomic number 28.",
    "French knights inspired the modern salute.",
    "Akon is the top ringtone-selling artist.",
    "The letter Z is the least used in English.",
    "The first computer virus was Creeper.",
    "The oldest webcam is the San Francisco FogCam.",
    "Doggerland once connected Britain to Europe.",
  ];

  /// Get a random fact (won't repeat last fact)
  String getRandomFact() {
    int index;

    // Ensure we don't get the same fact twice in a row
    do {
      index = _random.nextInt(_facts.length);
    } while (index == _lastFactIndex && _facts.length > 1);

    _lastFactIndex = index;
    return _facts[index];
  }

  /// Get total number of facts
  int get totalFacts => _facts.length;

  /// Get a specific fact by index (for testing)
  String getFactByIndex(int index) {
    if (index < 0 || index >= _facts.length) {
      return getRandomFact();
    }
    return _facts[index];
  }
}