import 'dart:math';

class FactsService {
  static final FactsService _instance = FactsService._internal();
  factory FactsService() => _instance;
  FactsService._internal();

  final Random _random = Random();
  int? _lastFactIndex;

  // 400+ Cool Facts Database
  final List<String> _facts = [
    // Science Facts (100)
    "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that's still edible!",
    "A day on Venus is longer than a year on Venus. It takes 243 Earth days to rotate once, but only 225 days to orbit the Sun.",
    "Bananas are berries, but strawberries aren't. Botanically, berries come from one flower with one ovary.",
    "Your brain uses 20% of your body's energy while being only 2% of your body weight.",
    "Octopuses have three hearts and blue blood. Two hearts pump blood to the gills, one pumps to the body.",
    "Water can boil and freeze at the same time - it's called the triple point!",
    "Glass is actually a liquid, not a solid - it just flows VERY slowly over centuries.",
    "A single lightning bolt contains enough energy to power a house for a month.",
    "Helium makes your voice higher because sound travels faster through it than air.",
    "Diamonds rain on Jupiter and Saturn - pressure turns methane into carbon crystals!",
    "Hot water freezes faster than cold water - it's called the Mpemba effect.",
    "Your body contains enough iron to make a 3-inch nail.",
    "Sound travels 4 times faster in water than in air.",
    "A teaspoon of honey is the life work of 12 bees.",
    "Graphite and diamonds are made of the same atoms, just arranged differently.",
    "Stomach acid is strong enough to dissolve metal, but mucus protects your stomach lining.",
    "A single bolt of lightning is 5 times hotter than the surface of the sun.",
    "Sharks existed before trees - they're over 400 million years old!",
    "Your DNA stretched out would reach from Earth to the Sun 600 times.",
    "Butterflies can taste with their feet to find good plants for laying eggs.",
    "Polar bears are nearly invisible to infrared cameras - their fur is that good at insulation!",
    "A single sneeze travels at 100 mph and can spray droplets 30 feet.",
    "Your fingernails grow 4 times faster than your toenails.",
    "The average person walks the equivalent of 5 times around the world in their lifetime.",
    "Your stomach gets a new lining every 3-4 days to prevent self-digestion.",
    "A cockroach can live for weeks without its head before dying of starvation.",
    "Your eyes can distinguish between 10 million different colors.",
    "The human body glows - you emit light 1,000 times weaker than your eyes can see.",
    "Your heart beats 100,000 times per day, pumping 2,000 gallons of blood.",
    "Humans shed about 40 pounds of skin in their lifetime.",
    "Your brain generates 25 watts of power while awake - enough to power a light bulb!",
    "Blood makes up 8% of your body weight.",
    "You produce enough saliva in your lifetime to fill two swimming pools.",
    "Your bones are 5 times stronger than steel of the same density.",
    "The human eye blinks an average of 4,200,000 times per year.",
    "Your body has enough carbon to make 900 pencils.",
    "Stomach acid (pH 1-2) can dissolve razor blades.",
    "You lose about 100 hairs per day naturally.",
    "Your tongue print is unique, just like fingerprints.",
    "The strongest muscle in the human body is the masseter (jaw muscle).",
    "Babies are born with 300 bones, but adults only have 206 (some fuse together).",
    "Your nose can remember 50,000 different scents.",
    "The average person spends 6 months of their life waiting for red lights to turn green.",
    "You can't breathe and swallow at the same time (try it!).",
    "Your brain uses 20 watts of power - less than a refrigerator light bulb.",
    "The human brain is 73% water - even 2% dehydration affects performance.",
    "Your heart will beat about 3 billion times in your lifetime.",
    "Humans are the only animals that blush.",
    "Your lungs have a surface area equal to a tennis court when flattened.",
    "You have more bacteria cells than human cells in your body (by count, not mass).",

    // Space Facts (50)
    "One million Earths could fit inside the Sun. The Sun contains 99.86% of the mass in our solar system.",
    "There are more stars in the universe than grains of sand on all Earth's beaches - about 10^24 stars!",
    "A teaspoon of neutron star material would weigh 6 billion tons on Earth.",
    "Saturn's rings are only about 30 feet thick despite being 175,000 miles wide.",
    "The footprints on the Moon will stay there for millions of years - there's no wind to blow them away!",
    "Space is completely silent - there's no atmosphere to carry sound.",
    "Venus spins backwards compared to most planets.",
    "Olympus Mons on Mars is 3 times taller than Mount Everest.",
    "The International Space Station travels at 17,500 mph - circling Earth every 90 minutes.",
    "A day on Mercury (59 Earth days) is longer than its year (88 Earth days).",
    "The Milky Way galaxy smells like rum and tastes like raspberries (based on chemical analysis).",
    "Neutron stars can spin 600 times per second.",
    "There's a planet made entirely of diamond (55 Cancri e) - it's twice the size of Earth!",
    "The Great Red Spot on Jupiter is a storm that's been raging for at least 400 years.",
    "Mars sunsets are blue, not orange.",
    "A year on Pluto is 248 Earth years long.",
    "The coldest place in the universe is on Earth - in a lab where scientists achieved 0.0000000001 degrees above absolute zero.",
    "Black holes aren't actually black - they glow due to radiation.",
    "The Sun loses a billion kilograms of mass per second.",
    "Saturn would float in water - its density is less than water's.",
    "The universe is expanding faster than the speed of light.",
    "There are rogue planets that drift through space without orbiting a star.",
    "Jupiter has 79 known moons (and counting).",
    "A sunset on Mars lasts about 2 hours.",
    "The hottest planet is Venus, not Mercury (despite being farther from the Sun).",
    "Earth isn't perfectly round - it's slightly flattened at the poles.",
    "The Hubble Space Telescope travels at 5 miles per second.",
    "Uranus rotates on its side - its axis is tilted 98 degrees.",
    "The Moon is moving away from Earth at 1.5 inches per year.",
    "Neptune takes 165 Earth years to orbit the Sun once.",
    "The Andromeda galaxy is approaching us at 250,000 mph.",
    "There's a water vapor cloud in space that contains 140 trillion times all the water on Earth.",
    "The temperature on the Moon ranges from -173°C at night to 127°C in the day.",
    "Mercury has ice in its polar craters despite being close to the Sun.",
    "Jupiter's moon Europa has a liquid ocean beneath its icy surface.",
    "The asteroid belt contains only 4% of the Moon's mass despite millions of asteroids.",
    "Light from some stars takes billions of years to reach us - we see the past when looking at space.",
    "Pluto hasn't completed one orbit around the Sun since its discovery in 1930.",
    "The Voyager 1 spacecraft is 14 billion miles from Earth and still sending data.",
    "Astronauts can't cry in space - tears just pool up in balls due to lack of gravity.",
    "Saturn's rings are made of ice and rock chunks, some as small as grains of sand.",
    "The Sun is so large that its gravity keeps planets in orbit from 3 billion miles away.",
    "Mars has the largest dust storms in the solar system - they can engulf the entire planet.",
    "The temperature at the core of the Sun is 15 million degrees Celsius.",
    "There are more possible chess games than atoms in the observable universe.",
    "The cosmic microwave background radiation is the oldest light in the universe (13.8 billion years old).",
    "Jupiter's magnetic field is 20,000 times stronger than Earth's.",
    "A supernova can outshine an entire galaxy for weeks.",
    "Time moves slower near massive objects due to gravity (proven by GPS satellites!).",
    "The nearest star system (Alpha Centauri) is 4.37 light years away - that's 25 trillion miles!",

    // Animal Facts (100)
    "Octopuses can taste with their arms. Each sucker has chemoreceptors to identify food.",
    "Cows have best friends and get stressed when separated from them.",
    "A group of flamingos is called a 'flamboyance' - perfectly named!",
    "Dolphins have names for each other and call out to specific individuals.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "A shrimp's heart is in its head.",
    "Elephants are the only animals that can't jump.",
    "A group of owls is called a 'parliament'.",
    "Penguins propose to their mates with a pebble - if accepted, they mate for life.",
    "Wombat poop is cube-shaped to prevent it from rolling away (they use it to mark territory).",
    "Sloths can hold their breath longer than dolphins - up to 40 minutes!",
    "A group of pugs is called a 'grumble'. Perfect!",
    "Horses can't breathe through their mouths - only through their noses.",
    "A snail can sleep for 3 years straight.",
    "Hummingbirds are the only birds that can fly backwards.",
    "Koalas sleep 22 hours a day.",
    "Giraffes have the same number of neck bones as humans (7).",
    "A cat has 32 muscles in each ear.",
    "Bees can recognize human faces.",
    "Crows can hold grudges against people for years.",
    "Male seahorses get pregnant, not females.",
    "A group of crows is called a 'murder'.",
    "Squirrels plant thousands of trees by forgetting where they buried their acorns.",
    "A pig's orgasm lasts 30 minutes.",
    "Otters have a pocket in their skin to store their favorite rock.",
    "Elephants can recognize themselves in mirrors.",
    "Dogs can smell your feelings - they detect hormonal changes.",
    "A blue whale's heart weighs 400 pounds.",
    "Mantis shrimp can punch so fast they boil the water around their fist.",
    "Cheetahs can't roar - they meow like house cats.",
    "A group of jellyfish is called a 'smack'.",
    "Butterflies taste with their feet.",
    "Turtles can breathe through their butts.",
    "A group of pandas is called an 'embarrassment'.",
    "Honeybees can fly up to 15 mph.",
    "A blue whale's tongue weighs as much as an elephant.",
    "Pigeons can do math - they can learn to count up to 9.",
    "Frogs drink water through their skin, not their mouths.",
    "A group of ravens is called an 'unkindness'.",
    "Parrots can live up to 80 years.",
    "Bats always turn left when exiting a cave.",
    "A group of ferrets is called a 'business'.",
    "Chameleons change color based on mood, not surroundings.",
    "A group of hedgehogs is called a 'prickle'.",
    "Wolves howl in different pitches so they sound like more wolves than they are.",
    "A polar bear's skin is black under its white fur.",
    "Kangaroos can't walk backwards.",
    "A group of rhinoceroses is called a 'crash'.",
    "Alligators can live up to 100 years.",
    "A group of zebras is called a 'dazzle'.",
    "Camels have three eyelids to protect against sand.",
    "A group of hippos is called a 'bloat'.",
    "Hummingbirds' hearts beat 1,200 times per minute.",
    "A group of porcupines is called a 'prickle'.",
    "Ostriches can run faster than horses and male ostriches can roar like lions.",
    "A group of alligators is called a 'congregation'.",
    "Reindeer eyes turn blue in winter to see better in the dark.",
    "A group of toads is called a 'knot'.",
    "Narwhals are real! Their tusk is actually a tooth with 10 million nerve endings.",
    "A group of sharks is called a 'shiver'.",
    "Goats have rectangular pupils.",
    "A group of fish is called a 'school' but also a 'shoal'.",
    "Rats laugh when tickled.",
    "A group of geese on the ground is a 'gaggle', but in the air it's a 'skein'.",
    "A woodpecker's tongue wraps around its brain to protect it from impact.",
    "A group of butterflies is called a 'kaleidoscope'.",
    "Axolotls can regenerate entire limbs.",
    "A group of bats is called a 'colony' or 'cloud'.",
    "Naked mole rats don't age - they look the same their entire life.",
    "A group of cats is called a 'clowder' or 'glaring'.",
    "Platypuses don't have stomachs.",
    "A group of larks is called an 'exaltation'.",
    "Lobsters pee out of their faces.",
    "A group of peacocks is called an 'ostentation'.",
    "Komodo dragons can reproduce asexually through parthenogenesis.",
    "A group of turkeys is called a 'rafter'.",
    "Vampire bats will adopt orphaned baby bats.",
    "A group of vultures is called a 'committee' when resting and a 'kettle' when flying.",
    "Octopuses have 9 brains - one main brain and one in each arm.",
    "A group of eagles is called a 'convocation'.",
    "Hummingbirds are the only birds that can hover in place.",
    "A group of magpies is called a 'mischief' or 'charm'.",
    "Flying squirrels don't actually fly - they glide up to 300 feet.",
    "A group of sparrows is called a 'host'.",
    "Sea horses mate for life and travel holding each other's tails.",
    "A group of swallows is called a 'gulp'.",
    "Honey badgers are immune to snake venom.",
    "A group of parrots is called a 'pandemonium'.",
    "Ants don't sleep.",
    "A group of ravens eating together is called an 'unkindness'.",
    "Electric eels can generate 600 volts of electricity.",
    "A group of starlings is called a 'murmuration'.",
    "Cuttlefish have three hearts and greenish-blue blood.",
    "A group of storks is called a 'mustering'.",
    "Octopuses can fit through any hole larger than their beak.",
    "A group of hawks is called a 'kettle' when flying or a 'cast' when perched.",
    "Tarantulas can live up to 30 years.",
    "A group of nightingales is called a 'watch'.",
    "Jellyfish have been around for 650 million years - before dinosaurs and trees!",
    "A group of doves is called a 'dule' or 'pitying'.",

    // History Facts (50)
    "Cleopatra lived closer to the Moon landing than to the building of the Great Pyramid.",
    "Oxford University is older than the Aztec Empire. Oxford started in 1096, Aztecs in 1428.",
    "The last woolly mammoth died in 2000 BC - 1,000 years after the pyramids were built!",
    "Nintendo was founded in 1889 as a playing card company.",
    "The Great Wall of China is NOT visible from space with the naked eye.",
    "Ancient Romans used urine as mouthwash (the ammonia whitened teeth).",
    "Forks weren't used in Europe until the 11th century - people ate with their hands.",
    "The shortest war in history lasted 38 minutes (Anglo-Zanzibar War, 1896).",
    "Napoleon wasn't actually short - at 5'7\", he was average height for his time.",
    "Ancient Egyptians slept on pillows made of stone.",
    "Vikings didn't wear horned helmets - that's a myth from opera costumes.",
    "The earliest recorded joke (1900 BC) was a fart joke.",
    "Ketchup was sold as medicine in the 1830s.",
    "The Eiffel Tower can grow 6 inches in summer due to thermal expansion.",
    "Hitler was nominated for the Nobel Peace Prize in 1939.",
    "Ancient Romans used to clean themselves with a shared sponge on a stick.",
    "Julius Caesar was kidnapped by pirates who demanded a ransom. He laughed and said he was worth more.",
    "The Leaning Tower of Pisa has never been straight.",
    "Ancient Greeks exercised naked - the word 'gymnasium' comes from 'gymnos' (naked).",
    "The first programmable computer weighed 27 tons (ENIAC, 1945).",
    "People used to mail children through the postal service in the early 1900s.",
    "The Ancient Olympics banned women from competing - or even watching.",
    "Benjamin Franklin never patented any of his inventions.",
    "The inventor of the Pringles can is buried in one.",
    "The first alarm clock could only ring at 4 am.",
    "Ancient Egyptians invented toothpaste 5,000 years ago.",
    "The first webcam was invented to watch a coffee pot at Cambridge University.",
    "In Ancient Rome, a commoner's dinner was bread dipped in wine.",
    "The oldest 'your mom' joke dates back to 3,500 BC in ancient Babylon.",
    "Ancient Egyptians wore makeup - both men and women used eyeliner.",
    "The Great Fire of London (1666) killed only 6 people officially.",
    "Thomas Edison didn't invent the light bulb - he improved it.",
    "The first telephone book had only 50 names and no phone numbers.",
    "Ancient Romans paid taxes in honey because it was so valuable.",
    "The French Revolution started in 1789, the same year the US Constitution was ratified.",
    "George Washington grew hemp but not marijuana.",
    "The bicycle was invented before the car.",
    "Sliced bread was invented in 1928.",
    "The first computer virus was created in 1983.",
    "Ancient Egyptians believed cats were sacred and mummified them.",
    "Shakespeare invented over 1,700 English words.",
    "The oldest known musical instrument is a 40,000-year-old flute made from bird bone.",
    "Ancient Romans had heated floors and running water.",
    "The first vending machine was invented in 1st century AD - it dispensed holy water.",
    "Abraham Lincoln is in the Wrestling Hall of Fame - he lost only 1 out of 300 matches.",
    "Ancient Mayans used chocolate as currency.",
    "The Colosseum could be filled or drained of water for mock sea battles.",
    "Queen Elizabeth II served in World War II as a mechanic and driver.",
    "The ice age ended only 12,000 years ago - humans existed throughout it!",
    "Ancient Greeks believed redheads turned into vampires after death.",

    // Technology & Modern Facts (50)
    "The first computer bug was an actual bug - a moth found in a computer in 1947.",
    "Your smartphone has more computing power than all of NASA in 1969 for the Moon landing.",
    "The first email was sent in 1971, and the @ symbol was chosen because it didn't appear in names.",
    "Nintendo's Game Boy had less computing power than a modern calculator.",
    "The first YouTube video was uploaded on April 23, 2005, titled 'Me at the zoo'.",
    "The first camera took 8 hours to take a single photo.",
    "The first computer mouse was made of wood.",
    "WiFi doesn't stand for anything - it's just a made-up marketing term.",
    "The first domain name ever registered was Symbolics.com in 1985.",
    "Google's first server rack was built from LEGO bricks.",
    "The average person unlocks their phone 150 times per day.",
    "Nokia used to make toilet paper before phones.",
    "The first webcam was used to monitor a coffee pot.",
    "The word 'robot' comes from Czech word 'robota' meaning forced labor.",
    "USB flash drives were invented in 1999.",
    "The first iPhone didn't have copy-paste or a video camera.",
    "Amazon was originally going to be called 'Cadabra'.",
    "The first computer weighed more than 27 tons.",
    "Bluetooth is named after a 10th-century Scandinavian king, Harald Bluetooth.",
    "The first website is still online - info.cern.ch.",
    "Humans didn't evolve to work 8 hours straight - it was an industrial revolution invention.",
    "The average smartphone has more processing power than a supercomputer from 1985.",
    "The first ever tweet was sent on March 21, 2006.",
    "The computer in your car is more powerful than the computers that landed astronauts on the Moon.",
    "The first banner ad on the internet had a 44% click rate (now it's less than 0.1%).",
    "PayPal was originally designed to send money between PalmPilots.",
    "The first CD pressed in the US was Bruce Springsteen's 'Born in the USA'.",
    "MP3 files delete sounds humans can't hear to save space.",
    "The first video game console was released in 1972 - the Magnavox Odyssey.",
    "Facebook's blue color scheme was chosen because Mark Zuckerberg is red-green colorblind.",
    "The first computer programmer was a woman - Ada Lovelace in the 1840s.",
    "YouTube's original purpose was as a dating site.",
    "The average person spends 7 years of their life on the internet.",
    "Social media addiction activates the same brain areas as drug addiction.",
    "Tesla cars have a 'dog mode' that keeps the AC on for pets.",
    "The first laptop (Osborne 1) weighed 24 pounds.",
    "QR codes were invented in 1994 to track automotive parts.",
    "The word 'meme' was coined in 1976, decades before internet memes.",
    "Linux is free and open source - it runs most of the internet's servers.",
    "The first hard drive (1956) was the size of a refrigerator and held 5 MB.",
    "Apple's first logo featured Isaac Newton sitting under an apple tree.",
    "The first iPod could hold 1,000 songs - now phones hold millions.",
    "Emails were around before the World Wide Web.",
    "The first GIF ever made was of a plane - created in 1987.",
    "Ctrl+Alt+Delete was supposed to be used rarely but became standard.",
    "The first commercially available mobile phone weighed 2 pounds.",
    "Spotify has over 70 million songs - it would take 270+ years to listen to all of them.",
    "The Mars Rover runs on solar panels and is controlled with 15-minute delay.",
    "3D printing can now print human organs using bio-ink.",
    "Self-driving cars have already driven over 20 million miles on public roads.",

    // Random Mind-Blowing Facts (50)
    "You can't hum while holding your nose closed. Try it!",
    "If you shuffle a deck of cards, the order has probably never existed before in history.",
    "Your skeleton is wet inside your body right now. Think about that.",
    "Time moves slower at higher altitudes due to gravity. Mountain climbers age faster!",
    "The probability of being born is about 1 in 400 trillion.",
    "You've never seen your face in person - only reflections and photos.",
    "You are younger than you think - parts of your body are only a few weeks old.",
    "The voices you hear in your head when reading are unique to you.",
    "You can see your nose all the time, but your brain ignores it.",
    "No piece of paper can be folded in half more than 7-8 times (try it!).",
    "The word 'swims' upside down is still 'swims'.",
    "The hashtag symbol (#) is called an octothorpe.",
    "You can't lick your elbow (90% of people try after reading this).",
    "Your tongue can't find a comfortable place to rest in your mouth once you think about it.",
    "You're now breathing manually. You're welcome.",
    "Thinking about your breathing makes it harder to breathe naturally.",
    "You can't stand backwards on stairs.",
    "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter of the alphabet.",
    "You read 'WTF' in your head differently than 'What the f***'.",
    "Right now, you're the oldest you've ever been and the youngest you'll ever be again.",
    "Technically, going to bed is just traveling 8 hours into the future.",
    "Your teeth are the only part of your skeleton you clean daily.",
    "Brushing your teeth is the only time you clean your skeleton.",
    "We put a man on the Moon before we put wheels on luggage.",
    "Someone out there has your dream job right now.",
    "Every photo of you is from when you were younger.",
    "Technically, your brain named itself.",
    "You've never been in an empty room - the air counts as something.",
    "The smell of freshly cut grass is actually a plant distress signal.",
    "Somewhere in the world, someone just started reading this exact fact at the same time as you.",
    "You will never experience total sensory deprivation - you can always hear your heartbeat and feel your breathing.",
    "Somewhere, there's a picture of you that you'll never see.",
    "Your parents carried you before you were born and will carry your memory after they're gone.",
    "Every person you've ever met knows a version of you that you've never met.",
    "There are people alive today who will live to see the year 2100.",
    "You share your birthday with approximately 20 million other people.",
    "At this very moment, someone is doing something for the last time in their life.",
    "Somewhere, someone is thinking about you right now.",
    "You'll never know if you've ever been in someone's dream.",
    "At some point, your parents put you down and never picked you up again.",
    "The first person to walk on Mars is alive right now somewhere on Earth.",
    "You've walked past hundreds of people who are now dead without knowing it.",
    "Your future self is watching you right now through memories.",
    "There's a date you'll die on, you just don't know when.",
    "Right now is the oldest the universe has ever been and the youngest it will ever be again.",
    "Someone out there remembers you randomly and smiles.",
    "You've survived 100% of your worst days so far.",
    "The next person you meet could become the most important person in your life.",
    "Somewhere, a tree is growing that will eventually be made into your coffin.",
    "You've probably forgotten more moments of your life than you remember.",
  ];

  /// Get a random fact (won't repeat last fact)
  String getRandomFact() {
    int index;

    // Ensure we don't get the same fact twice in a row
    do {
      index = _random.nextInt(_facts.length);
    } while (index == _lastFactIndex && _facts.length > 1);

    _lastFactIndex = index;
    return _facts[index];
  }

  /// Get total number of facts
  int get totalFacts => _facts.length;

  /// Get a specific fact by index (for testing)
  String getFactByIndex(int index) {
    if (index < 0 || index >= _facts.length) {
      return getRandomFact();
    }
    return _facts[index];
  }
}